# Generated by Django 4.2.1 on 2023-11-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_userprofile_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ProfileImage',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
