# Generated by Django 4.2.1 on 2023-11-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_userprofile_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ProfileImage',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
