# Generated by Django 4.2.1 on 2023-11-26 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_userprofile_profileimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ProfileImage',
        ),
    ]
