# Generated by Django 4.2.1 on 2023-11-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_userprofile_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Profileimage',
            field=models.ImageField(blank=True, null=True, upload_to='user/ProfileImage'),
        ),
    ]
