# Generated by Django 4.2.1 on 2023-11-26 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_userprofile_profileimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Profileimage',
        ),
    ]
