# Generated by Django 4.2.1 on 2023-11-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_userprofile_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='UserAvatar',
            field=models.ImageField(blank=True, null=True, upload_to='Users/Avatar'),
        ),
    ]
