# Generated by Django 4.2.1 on 2023-08-02 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductModule', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Categories',
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
