# Generated by Django 4.2.1 on 2023-08-04 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductModule', '0003_products_productgalleries_colors_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colors',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productgalleries',
            name='image',
        ),
        migrations.DeleteModel(
            name='Capacity',
        ),
        migrations.DeleteModel(
            name='Colors',
        ),
        migrations.DeleteModel(
            name='ProductGalleries',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
