# Generated by Django 4.2.1 on 2023-08-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductModule', '0005_capacity_colors_productgalleries_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
