# Generated by Django 4.2.1 on 2023-08-04 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductModule', '0006_alter_products_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProductGallery', to='ProductModule.productgalleries'),
        ),
        migrations.AlterField(
            model_name='products',
            name='capacity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductCapacity', to='ProductModule.capacity'),
        ),
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductColor', to='ProductModule.colors'),
        ),
    ]
