# Generated by Django 4.2.1 on 2023-08-04 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductModule', '0007_alter_products_gallery_alter_products_capacity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capacity',
            options={'verbose_name': 'Capacity', 'verbose_name_plural': 'Capacity'},
        ),
        migrations.AlterModelOptions(
            name='colors',
            options={'verbose_name': 'Color', 'verbose_name_plural': 'Colors'},
        ),
        migrations.AlterModelOptions(
            name='productgalleries',
            options={'verbose_name': 'ProductGallery', 'verbose_name_plural': 'ProductGallery'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
