# Generated by Django 4.2.1 on 2023-08-04 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductModule', '0008_alter_capacity_options_alter_colors_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Gallery',
        ),
        migrations.RemoveField(
            model_name='products',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='products',
            name='color',
        ),
        migrations.DeleteModel(
            name='Capacity',
        ),
        migrations.DeleteModel(
            name='Colors',
        ),
        migrations.DeleteModel(
            name='ProductGalleries',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
