# Generated by Django 4.2.1 on 2023-08-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductModule', '0010_capacity_colors_productgalleries_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
