# Generated by Django 4.2.1 on 2023-08-04 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductModule', '0011_products_count_products_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Gallery',
        ),
    ]
