# Generated by Django 4.2.1 on 2023-08-05 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductModule', '0012_remove_products_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcategory', to='ProductModule.categories'),
        ),
    ]
