# Generated by Django 4.2.1 on 2023-12-30 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductModule', '0024_brand_products_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
